name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: extension

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: |
        git clone -b 4.3.x-k https://github.com/krassowski/jupyterlab.git
        cd jupyterlab
        python -m pip install -e .[dev]
        jlpm run build

    - name: Build the extension
      run: |
        set -eux
        cd extension
        jlpm
        python -m pip install .[test]

        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "jupyterlab-launchpad.*OK"
        cd ..
        cd jupyterlab
        python -m jupyterlab.browser_check --dev-mode
